project:
  type: website

website:
  title: "Advanced R Environments"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: conditions_ko.qmd
        text: Conditions

      - href: debugging_ko.qmd
        text: Debugging

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right