project:
  type: website

website:
  title: "Advanced R Environments"

  navbar:
    left:

      - href: Conditions_ko (1).qmd
        text: Conditions

      - href: Debugging_ko.qmd
        text: Debugging

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    smooth-scroll: true